--- Makefile
+++ Makefile
@@ -728,7 +728,6 @@ KBUILD_CFLAGS += -mcpu=cortex-a76.cortex-a55
 KBUILD_AFLAGS += -mcpu=cortex-a76.cortex-a55
 else ifeq ($(cc-name),clang)
 KBUILD_CFLAGS += -mcpu=cortex-a55
-KBUILD_CFLAGS += -mtune=cortex-a55
 KBUILD_AFLAGS += -mcpu=cortex-a55
 endif
 
