 
name: CI

on: 
  schedule:
    - cron: "15 14 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch upstream
    - uses: 135e2/sync-upstream-repo@v0.1.5
      with:
      #Git upstream repo
        upstream_repo: https://github.com/vantoman/kernel_xiaomi_sm6150.git
        upstream_branch: eleven
        local_branch: main
	github_token: ${{ secrets.acode }}

